const { ipcMain } = require('electron')
const { session } = require('electron')
const { spawn } = require('node:child_process')
const path = require('node:path')
const fs = require('node:fs')
const logic = require('./ytdlp-logic')
const { PLATFORM_DEFS, PLATFORM_COOKIE_DOMAINS } = require('./platform-meta')

// ── 参考视频下载·yt-dlp 门（对齐 ffmpeg-gate 模式 + OpenCreator download/executor 架构）──
// 主进程只做 I/O（spawn/落盘/转码），策略（白名单/参数/档位/错误分类）全在 ytdlp-logic.js 纯函数层。

/** yt-dlp 路径解析（优先级：打包 resources/bin > 项目根 resources/bin > 开发 bin/win > 配置 externalPath > 系统 PATH） */
function resolveYtDlpPath(studioRoot, configStore) {
  if (process.resourcesPath) {
    const pkg = path.join(process.resourcesPath, 'bin', 'yt-dlp.exe')
    if (fs.existsSync(pkg)) return pkg
  }
  // 开发模式：项目根 resources/bin（与 ffmpeg 同目录，getStudioRoot 即项目根）
  const repoBin = path.join(studioRoot, 'resources', 'bin', 'yt-dlp.exe')
  if (fs.existsSync(repoBin)) return repoBin
  const devBin = path.join(studioRoot, 'bin', 'win', 'yt-dlp.exe')
  if (fs.existsSync(devBin)) return devBin
  const external = String(configStore?.get?.('ytdlp.externalPath') || '')
  if (external && fs.existsSync(external)) return external
  return 'yt-dlp'
}

/** safeOutputPath：realpath 校验输出不逃逸工作目录（对照 executor.ts download_output_escape） */
function safeOutputPath(workDir, filePath) {
  const resolved = path.resolve(filePath)
  let realDir = workDir
  try { realDir = fs.realpathSync(workDir) } catch (_) { /* 目录尚未创建时用解析路径 */ }
  if (!resolved.startsWith(path.resolve(realDir) + path.sep) && resolved !== path.resolve(realDir)) {
    throw new Error('download_output_escape: 输出路径越界')
  }
  return resolved
}

/**
 * 从内嵌浏览器平台分区导出 cookies 为 Netscape 文件（用户拍板方案：浏览器取 cookies）。
 * 同 thickShell-ipc _exportCookiesForPartition 口径；导不出（未登录/无 cookie）返回 null 不阻塞。
 */
async function exportCookiesForPlatform(platform, destPath) {
  try {
    const def = PLATFORM_DEFS[platform]
    const domains = PLATFORM_COOKIE_DOMAINS[platform]
    if (!def || !domains || !domains.length) return null
    const sess = session.fromPartition(def.partition)
    const seen = new Set()
    const unique = []
    for (const domain of domains) {
      for (const d of [domain, domain.replace(/^\./, '')]) {
        let cookies = []
        try { cookies = await sess.cookies.get({ domain: d }) } catch (_) { continue }
        for (const c of cookies) {
          const key = `${c.domain}|${c.path}|${c.name}`
          if (seen.has(key)) continue
          seen.add(key)
          unique.push(c)
        }
      }
    }
    if (!unique.length) return null
    let text = '# Netscape HTTP Cookie File\n# Generated by TinTin Client (embedded browser session)\n'
    for (const c of unique) {
      const d = c.domain.startsWith('.') ? c.domain : '.' + c.domain
      const exp = c.expirationDate ? Math.round(c.expirationDate) : Math.round(Date.now() / 1000 + 86400 * 30)
      text += `${d}\tTRUE\t${c.path || '/'}\t${c.secure ? 'TRUE' : 'FALSE'}\t${exp}\t${c.name}\t${c.value}\n`
    }
    fs.mkdirSync(path.dirname(destPath), { recursive: true })
    fs.writeFileSync(destPath, text, 'utf-8')
    return { count: unique.length, path: destPath }
  } catch (_) {
    return null
  }
}

/** 给参数集前置 --cookies（浏览器分区有登录态时；失败静默跳过不阻塞） */
async function withBrowserCookies(args, url, cookieDir) {
  try {
    const platform = logic.platformFromUrl(url)
    if (!platform) return args
    const exported = await exportCookiesForPlatform(platform, path.join(cookieDir, `cookies_${platform}.txt`))
    if (exported && exported.count > 0) return ['--cookies', exported.path, ...args]
  } catch (_) { /* 导出失败不带 cookies 继续跑 */ }
  return args
}

/** 执行 yt-dlp 收集完整输出（probe 用，一次性 JSON） */
function runYtDlpCollect(binPath, args, timeoutMs = 120000) {
  return new Promise((resolve, reject) => {
    const proc = spawn(binPath, args, { windowsHide: true })
    let stdout = ''
    let stderr = ''
    const timer = setTimeout(() => { proc.kill(); reject(new Error('yt-dlp 解析超时')) }, timeoutMs)
    proc.stdout.on('data', (d) => { stdout += d })
    proc.stderr.on('data', (d) => { stderr += d })
    proc.on('error', (e) => { clearTimeout(timer); reject(e) })
    proc.on('close', (code) => {
      clearTimeout(timer)
      resolve({ code, stdout, stderr })
    })
  })
}

function createYtdlpGate(ipcMain, input) {
  const { getStudioRoot, getCacheDir, configStore } = input

  // ── ffmpeg/ffprobe 原语（同 ffmpeg-gate getBinDir 口径：打包 resources/bin > dev bin/win > PATH）──
  function getBinDir() {
    if (process.resourcesPath) {
      const pkgBin = path.join(process.resourcesPath, 'bin')
      if (fs.existsSync(pkgBin)) return pkgBin
    }
    const devBin = path.join(getStudioRoot(), 'bin', 'win')
    if (fs.existsSync(devBin)) return devBin
    return ''
  }
  function getFfmpegPath() {
    const exe = getBinDir() && path.join(getBinDir(), 'ffmpeg.exe')
    return exe && fs.existsSync(exe) ? exe : 'ffmpeg'
  }
  function getFfprobePath() {
    const exe = getBinDir() && path.join(getBinDir(), 'ffprobe.exe')
    return exe && fs.existsSync(exe) ? exe : 'ffprobe'
  }
  /** ffprobe JSON（返回原始 parsed，含 streams；供兼容判定/元数据） */
  function runFfprobe(file) {
    return new Promise((resolve, reject) => {
      const proc = spawn(getFfprobePath(), ['-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', file], { windowsHide: true })
      let stdout = ''
      proc.stdout.on('data', (d) => { stdout += d })
      proc.on('error', reject)
      proc.on('close', (code) => {
        if (code !== 0) { reject(new Error('ffprobe failed')); return }
        try { resolve(JSON.parse(stdout)) } catch (e) { reject(e) }
      })
    })
  }
  /** ffmpeg 原子转码（归一化用，5 分钟兑底超时） */
  function runFfmpegArgs(args) {
    return new Promise((resolve, reject) => {
      const proc = spawn(getFfmpegPath(), args, { windowsHide: true })
      let stderr = ''
      proc.stderr.on('data', (d) => { stderr += d })
      const timer = setTimeout(() => { try { proc.kill() } catch (_) {} reject(new Error('ffmpeg 转码超时')) }, 5 * 60 * 1000)
      proc.on('error', (e) => { clearTimeout(timer); reject(e) })
      proc.on('close', (code) => {
        clearTimeout(timer)
        if (code === 0) resolve(true)
        else reject(new Error(`ffmpeg failed: ${stderr.slice(-500)}`))
      })
    })
  }

  ipcMain.handle('ytdlp:status', () => {
    const binPath = resolveYtDlpPath(getStudioRoot(), configStore)
    const external = binPath !== 'yt-dlp'
    return { available: external, path: binPath, external }
  })

  // probe：--dump-single-json → 宽容解析 + 档位生成（对照 executor.ts probe + probe-parser）
  ipcMain.handle('ytdlp:probe', async (_e, payload) => {
    const url = String(payload?.url || '').trim()
    if (!logic.isSupportedUrl(url)) {
      return { error: logic.downloadErrorText('unsupported_source') }
    }
    const proxy = String(payload?.proxy || configStore?.get?.('ytdlp.proxy') || '')
    const binPath = resolveYtDlpPath(getStudioRoot(), configStore)
    const cookieDir = path.join(getCacheDir(), 'video_download')
    try {
      const { code, stdout, stderr } = await runYtDlpCollect(binPath, await withBrowserCookies(logic.buildProbeArgs(url, proxy), url, cookieDir))
      if (code !== 0 || !stdout.trim()) {
        const cls = logic.classifyDownloadError(stderr)
        return { error: logic.downloadErrorText(cls.code), code: cls.code, stderrTail: cls.stderrTail }
      }
      // stdout 可能混入 --print 的附加行：取第一个 { 起的 JSON 主体
      const jsonStart = stdout.indexOf('{')
      const probe = logic.parseProbeJson(JSON.parse(stdout.slice(jsonStart)))
      const options = logic.createDownloadOptions(probe)
      return { probe, options }
    } catch (e) {
      const cls = logic.classifyDownloadError(String(e?.message || e))
      return { error: `${logic.downloadErrorText(cls.code)}（${e?.message || e}）`, code: cls.code }
    }
  })

  // download：按档位下载 → 落盘 video_download → 播放兼容归一化 → ffprobe 元数据。
  // 进度经 event.sender.send('ytdlp:progress', {...}) 推送（对齐 montage 分割的实时反馈诉求）。
  ipcMain.handle('ytdlp:download', async (event, payload) => {
    const url = String(payload?.url || '').trim()
    const option = payload?.option || {}
    if (!logic.isSupportedUrl(url)) {
      return { error: logic.downloadErrorText('unsupported_source') }
    }
    const binPath = resolveYtDlpPath(getStudioRoot(), configStore)
    const proxy = String(payload?.proxy || configStore?.get?.('ytdlp.proxy') || '')
    const jobDir = path.join(getCacheDir(), 'video_download', `${Date.now().toString(36)}${Math.floor(Math.random() * 1e6).toString(36)}`)
    fs.mkdirSync(jobDir, { recursive: true })
    const sender = event.sender
    const report = (p) => { try { sender.send('ytdlp:progress', p) } catch (_) { /* 窗口已关 */ } }

    const sendProgress = (phase, pct) => report({ phase, pct })
    sendProgress('download', 2)

    const args = option.mediaType === 'audio'
      ? logic.buildAudioDownloadArgs({ url, formatId: option.audioFormatId, kbps: option.kbps || 192, outTemplate: logic.outTemplateFor(jobDir), ffmpegDir: getBinDir() || '', proxy })
      : logic.buildVideoDownloadArgs({ url, formatId: option.videoFormatId, audioFormatId: option.audioFormatId, outTemplate: logic.outTemplateFor(jobDir), ffmpegDir: getBinDir() || '', proxy })

    const finalArgs = await withBrowserCookies(args, url, path.join(getCacheDir(), 'video_download'))
    const downloaded = await new Promise((resolve) => {
      const proc = spawn(binPath, finalArgs, { windowsHide: true })
      let stderr = ''
      let printedPath = ''
      let pending = ''
      proc.stdout.on('data', (d) => {
        // --print after_move:filepath 的产物路径从 stdout 末行取（不猜文件名）
        pending += String(d)
        let idx
        while ((idx = pending.indexOf('\n')) >= 0) {
          const line = pending.slice(0, idx).trim(); pending = pending.slice(idx + 1)
          if (line && !line.startsWith('[')) printedPath = line
          const p = logic.parseProgressLine(line)
          if (p) sendProgress(p.phase, p.pct)
        }
      })
      proc.stderr.on('data', (d) => { stderr += d })
      proc.on('error', (e) => resolve({ error: String(e?.message || e) }))
      proc.on('close', (code) => {
        if (pending.trim() && !pending.trim().startsWith('[')) printedPath = pending.trim()
        if (code !== 0) {
          const cls = logic.classifyDownloadError(stderr)
          resolve({ error: logic.downloadErrorText(cls.code), code: cls.code, stderrTail: cls.stderrTail })
          return
        }
        resolve({ printedPath })
      })
    })
    if (downloaded.error) { sendProgress('error', 0); return downloaded }

    // 产物定位：--print 优先，回退目录内唯一文件（排除 .part 残片）
    let produced = downloaded.printedPath
    if (!produced) {
      const files = fs.readdirSync(jobDir).filter((f) => !f.endsWith('.part'))
      if (files.length === 1) produced = path.join(jobDir, files[0])
    }
    if (!produced || !fs.existsSync(produced)) {
      return { error: '下载完成但未找到产物文件，请重试' }
    }
    produced = safeOutputPath(jobDir, produced)
    sendProgress('normalize', 98)

    // 播放兼容归一化（对照 normalizeVideoForPlayback：不兼容转 .playable.mp4，成功删原件）
    let finalPath = produced
    let normalized = false
    try {
      const info = await runFfprobe(produced)
      if (!logic.isPlaybackCompatible(info)) {
        const dst = produced.replace(/\.[^.]+$/, '') + '.playable.mp4'
        await runFfmpegArgs(logic.buildNormalizeArgs(produced, dst, info))
        if (fs.existsSync(dst) && fs.statSync(dst).size > 1024) {
          const recheck = await runFfprobe(dst)
          if (logic.isPlaybackCompatible(recheck)) {
            try { fs.unlinkSync(produced) } catch (_) { /* 删原件失败不阻断 */ }
            finalPath = dst
            normalized = true
          }
        }
        if (!normalized) {
          return { error: logic.downloadErrorText('download_playback_conversion_failed'), code: 'download_playback_conversion_failed' }
        }
      }
      const meta = await runFfprobe(finalPath).catch(() => null)
      sendProgress('done', 100)
      return {
        path: finalPath,
        fileName: path.basename(finalPath),
        normalized,
        meta: meta ? { width: meta.width, height: meta.height, duration: meta.duration } : null,
      }
    } catch (e) {
      return { error: `下载后处理失败：${e?.message || e}` }
    }
  })

  // 归档：把产物复制到用户指定位置（保存到本机，对齐 server:downloadResult 通道惯例）
  ipcMain.handle('ytdlp:saveAs', async (_e, payload) => {
    const src = String(payload?.src || '')
    const dst = String(payload?.dst || '')
    if (!src || !dst || src === dst) return { error: '参数缺失' }
    try {
      fs.mkdirSync(path.dirname(dst), { recursive: true })
      fs.copyFileSync(src, dst)
      return { ok: true }
    } catch (e) {
      return { error: `保存失败：${e?.message || e}` }
    }
  })
}

module.exports = { createYtdlpGate, resolveYtDlpPath, safeOutputPath }
